# Generated by Django 4.1.3 on 2022-11-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=20)),
                ('runs', models.FloatField(default=0)),
                ('team', models.CharField(max_length=20)),
                ('records', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
